export const IMAGES = {
  //Onboarding image
  IC_ONBOARDING_TOP: require('../../assets/images/onboardingTop.png'),
  //ICONS
  IC_ARROW_RIGHT: require('../../assets/images/arrow_right.png'),
  IC_ARROW_LEFT: require('../../assets/images/arrow_left.png'),
  IC_ARROW_DOWN: require('../../assets/images/arrow_down.png'),
  IC_CHECK: require('../../assets/images/check.png'),
  IC_PLUS: require('../../assets/images/plus.png'),
  IC_CHEVRON_RIGHT: require('../../assets/images/chevron_right.png'),
  IC_CUSTOMER: require('../../assets/images/ic_customer.png'),
  IC_AGENCY: require('../../assets/images/ic_Agency.png'),
  IC_ARCHITECT: require('../../assets/images/ic_architect.png'),
  IC_USER: require('../../assets/images/user.png'),
  IC_SEARCH: require('../../assets/images/search.png'),
  IC_LOCATION: require('../../assets/images/location.png'),
  IC_HOME: require('../../assets/images/home.png'),
  IC_FILE: require('../../assets/images/file_text.png'),
  IC_BELL: require('../../assets/images/bell.png'),
  IC_STAR: require('../../assets/images/star.png'),
  IC_EYE: require('../../assets/images/eye.png'),
  IC_VERIFY: require('../../assets/images/verified.png'),
  IC_DOWNLOAD: require('../../assets/images/download.png'),
  IC_CALL: require('../../assets/images/phone.png'),
  IC_CROSS: require('../../assets/images/cross.png'),
  IC_MESSAGE: require('../../assets/images/message.png'),
  FILLED_CHECKBOX: require('../../assets/images/FilledCheckbox.png'),
  UNFILLED_CHECKBOX: require('../../assets/images/UnFilledCheckbox.png'),
};
