export const IMAGES = {
  //Onboarding image
  IC_ONBOARDING_TOP: require('../../assets/images/onboardingTop.png'),
  //Agency Purchase Plan
  PAYMENT_1: require('../../assets/images/payment1.png'),
  PAYMENT_2: require('../../assets/images/payment2.png'),
  PAYMENT_3: require('../../assets/images/payment3.png'),

  DIAMOND_1: require('../../assets/images/diamond1.png'),
  DIAMOND_2: require('../../assets/images/diamond2.png'),
  DIAMOND_3: require('../../assets/images/diamond3.png'),

  //ICONS
  IC_ARROW_RIGHT: require('../../assets/images/arrow_right.png'),
  IC_ARROW_LEFT: require('../../assets/images/arrow_left.png'),
  IC_ARROW_DOWN: require('../../assets/images/arrow_down.png'),
  IC_CHECK: require('../../assets/images/check.png'),
  IC_PLUS: require('../../assets/images/plus.png'),
  IC_CHEVRON_RIGHT: require('../../assets/images/chevron_right.png'),
  IC_CUSTOMER: require('../../assets/images/ic_customer.png'),
  IC_AGENCY: require('../../assets/images/ic_Agency.png'),
  IC_ARCHITECT: require('../../assets/images/ic_architect.png'),
  IC_USER: require('../../assets/images/user.png'),
  IC_SEARCH: require('../../assets/images/search.png'),
  IC_LOCATION: require('../../assets/images/location.png'),
  IC_HOME: require('../../assets/images/home.png'),
  IC_FILE: require('../../assets/images/file_text.png'),
  IC_BELL: require('../../assets/images/bell.png'),
  IC_STAR: require('../../assets/images/star.png'),
  IC_EYE: require('../../assets/images/eye.png'),
  IC_VERIFY: require('../../assets/images/verified.png'),
  IC_DOWNLOAD: require('../../assets/images/download.png'),
  IC_CALL: require('../../assets/images/phone.png'),
  IC_CROSS: require('../../assets/images/cross.png'),
  IC_MESSAGE: require('../../assets/images/message.png'),
  IC_BRIEFCASE: require('../../assets/images/briefcase.png'),
  IC_LOGOUT: require('../../assets/images/log_out.png'),
  IC_PENCIL: require('../../assets/images/pencil.png'),
  IC_CAMERA: require('../../assets/images/camera.png'),
  IC_DUSTBIN: require('../../assets/images/dustbin.png'),
  IC_PROFILE_DOTS: require('../../assets/images/profileBG.png'),
  FILLED_CHECKBOX: require('../../assets/images/FilledCheckbox.png'),
  UNFILLED_CHECKBOX: require('../../assets/images/UnFilledCheckbox.png'),
  FILLED_RADIO: require('../../assets/images/selectedRadio.png'),
  UNFILLED_RADIO: require('../../assets/images/unselectRadio.png'),
  AGENCY_GRP: require('../../assets/images/agecyGrp.png'),
  IC_PLUS_FILES: require('../../assets/images/plusFiles.png'),
  IC_ADDPROJECTS: require('../../assets/images/addProjects.png'),
  IC_UPLOAD: require('../../assets/images/upload.png'),
  MESSAGE_BOX: require('../../assets/images/messageBox.png'),
};
